package br.senai.sp.jandira.clientesapp.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Cores do Tema Claro
val primaryLight = Color(0xFF3A693B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFBBF0B6)
val onPrimaryContainerLight = Color(0xFF225025)
val secondaryLight = Color(0xFF52634F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD5E8CF)
val onSecondaryContainerLight = Color(0xFF3B4B39)
val tertiaryLight = Color(0xFF39656B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBCEBF1)
val onTertiaryContainerLight = Color(0xFF1F4D53)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF7FBF1)
val onBackgroundLight = Color(0xFF181D17)

// Cores do Tema Escuro
val primaryDark = Color(0xFF9FD49B)
val onPrimaryDark = Color(0xFF073910)
val primaryContainerDark = Color(0xFF225025)
val onPrimaryContainerDark = Color(0xFFBBF0B6)
val secondaryDark = Color(0xFFB9CCB4)
val onSecondaryDark = Color(0xFF253424)
val secondaryContainerDark = Color(0xFF3B4B39)
val onSecondaryContainerDark = Color(0xFFD5E8CF)
val tertiaryDark = Color(0xFFA1CED5)
val onTertiaryDark = Color(0xFF00363C)
val tertiaryContainerDark = Color(0xFF1F4D53)
val onTertiaryContainerDark = Color(0xFFBCEBF1)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF10140F)
val onBackgroundDark = Color(0xFFE0E4DB)